name: Singularity build
on: workflow_dispatch

jobs:
  build-containers:
    runs-on: ubuntu-latest

    name: Build Singularity container
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Install Singularity dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            pkg-config

      - name: Install Singularity
        env:
          SINGULARITY_VERSION: 3.9.0
          GOPATH: /tmp/go
      
        run: |
          mkdir -p $GOPATH
          sudo mkdir -p /usr/local/var/singularity/mnt && \
          mkdir -p $GOPATH/src/github.com/sylabs && \
          cd $GOPATH/src/github.com/sylabs && \
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz | \
          tar xzv && \
          cd singularity-ce-${SINGULARITY_VERSION} && \
          ./mconfig -p /usr/local && \
          make -C builddir && \
          sudo make -C builddir install          

      - name: Check out code for the container build
        uses: actions/checkout@v2

      - name: Login to GitHub package registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ github.actor }} --password-stdin oras://ghcr.io

      - name: Build and deploy Singularity container
        run: |
            recipe=singularity.def
            basename=prepy-wrapper
            tag=latest
            # Build container
            sudo -E singularity build $basename.sif $recipe
            # Push container and name by tag
            url="oras://ghcr.io/${{ github.repository_owner }}/${basename}:${tag}"
            echo "Pushing container to $url"
            singularity push $basename.sif $url
            rm $basename.sif
